# Site settings
title: Onelife Media
email: support@onelifemedia.com
description: > # this means to ignore newlines until "baseurl:"
    Through our unique perspective, style, and technical know-how, Onelife 
    Media can help your company reach its goal with strategic design, 
    eye-catching imagery, and innovative software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onelifemedia.com" # the base hostname & protocol for your site
twitter_username: onelifemedia
github_username:  onelifemedia
gs_id: UA-55025316-1

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "blog/page:num"

exclude:
  - ".gitignore"
  - ".DS_Store"
